apiVersion: apps/v1
kind: Deployment
metadata:
  name: buy-nest-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: buy-nest-frontend
  template:
    metadata:
      labels:
        app: buy-nest-frontend
    spec:
      containers:
      - name: buy-nest-frontend
        image: ${FRONTEND_IMAGE_NAME}:${FRONTEND_IMAGE_TAG}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: buy-nest-frontend-service
spec:
  selector:
    app: buy-nest-frontend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
  type: LoadBalancer  
