type: object
properties:
  id:
    type: string
    example: "64fbf2d89e7c95a72f0a98b5"
  name:
    type: string
    example: "Product Name"
  description:
    type: string
    example: "Product description"
  price:
    type: number
    example: 99.99
  category:
    $ref: './Category.yaml'
  brandNamw:
    type: string
    example: "Brand Name"
  modelName:
    type: string
    example: "Model Name"
  stock:
    type: integer
    example: 100
  images:
    type: array
    items:
      type: string
      example: "https://example.com/image1.jpg"
  createdAt:
    type: string
    format: date-time
  updatedAt:
    type: string
    format: date-time
required:
  - id
  - name
  - price
