openapi: 3.1.0
info:
  title: My API
  version: 1.0.0
  description: A sample API with YAML references

servers:
  - url: http://localhost:5000

paths:
  $ref: './paths/path.yaml'

components:
  schemas:
    Product:
      $ref: './components/schemas/Product.yaml'
    User:
      $ref: './components/schemas/User.yaml'
